[package]
name = "fuzzer_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1" # Downgraded to match ratatui's dependency
ratatui = "0.29.0"
ratatui-explorer = "0.2.0"

[dev-dependencies]
tempfile = "3.10.1"
